apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app-container
        image: ajinkyadesai2323/voting-app:latest 
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            value: "voting-db-instance-instance-1.cojuqi8e8u3q.us-east-1.rds.amazonaws.com"
          - name: DB_USER
            value: "admin"
          - name: DB_PASSWORD
            value: "ajinkya123"
          - name: DB_NAME
            value: "mysql"    # <--- Updated based on your screenshot
          - name: DB_PORT
            value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80        
    targetPort: 3000 
  selector:
    app: voting-app